# .github/workflows/scheduled-builds.yml
name: Cache

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'
jobs:
  build:
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies & play script
        env:
          ACCOUNT_JSON: ${{ secrets.HOROSCOPE_ACCOUNT_JSON }}
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install lxml
          pip install beautifulsoup4
          python  ${{ github.workspace }}/cache.py
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.15.4
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: './cache'

  # Deployment job
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
